services:
  school-stats-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    extra_hosts:
      - "bnisapi.braeburn.ac.ke:192.168.1.21"
    restart: unless-stopped
